import type { Metadata } from "next";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/background/aurora-background";
import { ThemeSwitcher } from "@/components/layouts/ThemeToggler/ThemeSwitcher";
import { ThemeProvider } from "next-themes";
import FloatingDockInvertedComponent from "@/components/layouts/dock/FloatingDockInverted";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuroraBackground>
            <TooltipProvider>
              <div className="min-h-screen z-10 w-full flex flex-col">
                {/* Theme switcher */}
                <div className="absolute  top-2 right-2 z-50">
                  <ThemeSwitcher />
                </div>

                {/* Dock section */}
                <div className="w-full">
                  <div className="p-4">
                    <FloatingDockInvertedComponent />
                  </div>
                </div>

                {/* Content section */}
                <div className="flex-1 px-8 py-4 overflow-auto">{children}</div>
              </div>
            </TooltipProvider>
          </AuroraBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
