import type { Metadata } from "next";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";
import { ThemeSwitcher } from "@/components/layouts/ThemeToggler/ThemeSwitcher";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuroraBackground>
            <div className="z-10">
              <div className="absolute top-4 right-4">
                <ThemeSwitcher />
              </div>
              {children}
            </div>
          </AuroraBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
